language: r

sudo: false

r: devel

cache: packages

latex: true

fortran: true

script: 
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check corrsurv*tar.gz

after_script:
  - tar -ztvf corrsurv_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL

after_failure:
- cat corrsurv.Rcheck/00*
